### ISSUE TITLE
Magento 2.3.3 incompatibility

### ISSUE THREAD

**Issue by chris-pook** [ebizmarts/magento2-mandrill-smtp#7]
This module is not compatible with the Magento 2.3.3 release due to an argument type hint which is no longer correct for the Model\Transport\Smtp::sendMessage() function.

To replicate, install and configure the module. Then try to trigger an email send such as forgotten password.

Full error:
```
PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Ebizmarts\MandrillSmtp\Model\Transport\Smtp::sendMessage() must implement interface Magento\Framework\Mail\MessageInterface, instance of Magento\Framework\Mail\EmailMessage given, called in /var/www/vendor/ebizmarts/magento2-mandrillsmtp/Plugin/Mail/TransportPlugin.php on line 42 and defined in /var/www/vendor/ebizmarts/magento2-mandrillsmtp/Model/Transport/Smtp.php:48

Stack trace:
#0 /var/www/vendor/ebizmarts/magento2-mandrillsmtp/Plugin/Mail/TransportPlugin.php(42): Ebizmarts\MandrillSmtp\Model\Transport\Smtp->sendMessage(Object(Magento\Framework\Mail\EmailMessage))
#1 /var/www/vendor/magento/framework/Interception/Interceptor.php(135): Ebizmarts\MandrillSmtp\Plugin\Mail\TransportPlugin->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(Closure))
#2 /var/www/vendor/dotmailer/dotmailer-magento2-extension/Plugin/TransportPlugin.php(75): Magento\Email\Mode
```

**Comment by gonzaloebiz** [comment]
Please take a look at https://github.com/ebizmarts/magento2-mandrill-smtp/issues/6

Best

**Comment by chris-pook** [comment]
Ah sorry, yup duplicate issue from me.
